[2024-03-08T15:11:28.439+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.unzip_archive scheduled__2024-03-07T00:33:00+00:00 [queued]>
[2024-03-08T15:11:28.441+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.unzip_archive scheduled__2024-03-07T00:33:00+00:00 [queued]>
[2024-03-08T15:11:28.441+0530] {taskinstance.py:2193} INFO - Starting attempt 16 of 17
[2024-03-08T15:11:28.445+0530] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): unzip_archive> on 2024-03-07 00:33:00+00:00
[2024-03-08T15:11:28.450+0530] {standard_task_runner.py:60} INFO - Started process 19011 to run task
[2024-03-08T15:11:28.453+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'unzip_archive', 'scheduled__2024-03-07T00:33:00+00:00', '--job-id', '689', '--raw', '--subdir', 'DAGS_FOLDER/Data_analysis.py', '--cfg-path', '/var/folders/th/tnjyp6yd1cj78nysn5t4jl6h0000gn/T/tmpoej2mvmb']
[2024-03-08T15:11:28.453+0530] {standard_task_runner.py:88} INFO - Job 689: Subtask unzip_archive
[2024-03-08T15:20:31.113+0530] {process_utils.py:131} INFO - Sending 15 to group 19011. PIDs of all processes in the group: [19011]
[2024-03-08T15:20:31.114+0530] {process_utils.py:86} INFO - Sending the signal 15 to group 19011
[2024-03-08T15:20:31.118+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=19011, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='15:11:28') (19011) terminated with exit code -15
[2024-03-08T15:20:34.863+0530] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: weather_data_pipeline.unzip_archive scheduled__2024-03-07T00:33:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-03-08T15:20:34.867+0530] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: weather_data_pipeline.unzip_archive scheduled__2024-03-07T00:33:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-03-08T15:20:34.867+0530] {local_task_job_runner.py:160} INFO - Task is not able to be run
