[2024-03-03T02:22:57.475+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.extract_and_filter_data manual__2024-03-02T19:24:10.303999+00:00 [queued]>
[2024-03-03T02:22:57.477+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.extract_and_filter_data manual__2024-03-02T19:24:10.303999+00:00 [queued]>
[2024-03-03T02:22:57.477+0530] {taskinstance.py:2193} INFO - Starting attempt 21 of 21
[2024-03-03T02:22:57.482+0530] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_and_filter_data> on 2024-03-02 19:24:10.303999+00:00
[2024-03-03T02:22:57.485+0530] {standard_task_runner.py:60} INFO - Started process 35150 to run task
[2024-03-03T02:22:57.488+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'extract_and_filter_data', 'manual__2024-03-02T19:24:10.303999+00:00', '--job-id', '393', '--raw', '--subdir', 'DAGS_FOLDER/Data_analysis.py', '--cfg-path', '/var/folders/th/tnjyp6yd1cj78nysn5t4jl6h0000gn/T/tmpqla_tokq']
[2024-03-03T02:22:57.489+0530] {standard_task_runner.py:88} INFO - Job 393: Subtask extract_and_filter_data
[2024-03-03T02:22:57.505+0530] {task_command.py:423} INFO - Running <TaskInstance: weather_data_pipeline.extract_and_filter_data manual__2024-03-02T19:24:10.303999+00:00 [running]> on host aniks-macbook-air.local
[2024-03-03T02:22:57.525+0530] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='extract_and_filter_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-02T19:24:10.303999+00:00' AIRFLOW_CTX_TRY_NUMBER='21' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-02T19:24:10.303999+00:00'
[2024-03-03T02:22:57.527+0530] {pipeline.py:196} INFO - Missing pipeline option (runner). Executing pipeline using the default runner: DirectRunner.
[2024-03-03T02:22:57.611+0530] {translations.py:712} INFO - ==================== <function annotate_downstream_side_inputs at 0x12aa8a7a0> ====================
[2024-03-03T02:22:57.611+0530] {translations.py:712} INFO - ==================== <function fix_side_input_pcoll_coders at 0x12aa8a8e0> ====================
[2024-03-03T02:22:57.612+0530] {translations.py:712} INFO - ==================== <function pack_combiners at 0x12aa8ae80> ====================
[2024-03-03T02:22:57.612+0530] {translations.py:712} INFO - ==================== <function lift_combiners at 0x12aa8af20> ====================
[2024-03-03T02:22:57.612+0530] {translations.py:712} INFO - ==================== <function expand_sdf at 0x12aa8b100> ====================
[2024-03-03T02:22:57.612+0530] {translations.py:712} INFO - ==================== <function expand_gbk at 0x12aa8b1a0> ====================
[2024-03-03T02:22:57.612+0530] {translations.py:712} INFO - ==================== <function sink_flattens at 0x12aa8b2e0> ====================
[2024-03-03T02:22:57.612+0530] {translations.py:712} INFO - ==================== <function greedily_fuse at 0x12aa8b380> ====================
[2024-03-03T02:22:57.612+0530] {translations.py:712} INFO - ==================== <function read_to_impulse at 0x12aa8b420> ====================
[2024-03-03T02:22:57.613+0530] {translations.py:712} INFO - ==================== <function impulse_to_input at 0x12aa8b4c0> ====================
[2024-03-03T02:22:57.613+0530] {translations.py:712} INFO - ==================== <function sort_stages at 0x12aa8b740> ====================
[2024-03-03T02:22:57.613+0530] {translations.py:712} INFO - ==================== <function add_impulse_to_dangling_transforms at 0x12aa8b880> ====================
[2024-03-03T02:22:57.613+0530] {translations.py:712} INFO - ==================== <function setup_timer_mapping at 0x12aa8b6a0> ====================
[2024-03-03T02:22:57.613+0530] {translations.py:712} INFO - ==================== <function populate_data_channel_coders at 0x12aa8b7e0> ====================
[2024-03-03T02:22:57.614+0530] {statecache.py:234} INFO - Creating state cache with size 104857600
[2024-03-03T02:22:57.614+0530] {worker_handlers.py:922} INFO - Created Worker handler <apache_beam.runners.portability.fn_api_runner.worker_handlers.EmbeddedWorkerHandler object at 0x12a97b010> for environment ref_Environment_default_environment_1 (beam:env:embedded_python:v1, b'')
[2024-03-03T02:22:57.988+0530] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anikbhowmick/Python/Big_Data_Assignment/A02/airflow_env/airflow/dags/Data_analysis.py", line 65, in extract_and_filter
    return json.dumps([processed_data])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PCollection is not JSON serializable
[2024-03-03T02:22:57.992+0530] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=weather_data_pipeline, task_id=extract_and_filter_data, execution_date=20240302T192410, start_date=20240302T205257, end_date=20240302T205257
[2024-03-03T02:22:57.995+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 393 for task extract_and_filter_data (Object of type PCollection is not JSON serializable; 35150)
[2024-03-03T02:22:58.041+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-03T02:22:58.050+0530] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
