[2024-03-08T00:11:29.563+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.unzip_archive scheduled__2024-03-05T00:33:00+00:00 [queued]>
[2024-03-08T00:11:29.565+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.unzip_archive scheduled__2024-03-05T00:33:00+00:00 [queued]>
[2024-03-08T00:11:29.565+0530] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-08T00:11:29.568+0530] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): unzip_archive> on 2024-03-05 00:33:00+00:00
[2024-03-08T00:11:29.573+0530] {standard_task_runner.py:60} INFO - Started process 1948 to run task
[2024-03-08T00:11:29.575+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_pipeline', 'unzip_archive', 'scheduled__2024-03-05T00:33:00+00:00', '--job-id', '543', '--raw', '--subdir', 'DAGS_FOLDER/Data_analysis.py', '--cfg-path', '/var/folders/th/tnjyp6yd1cj78nysn5t4jl6h0000gn/T/tmpoyvy5fs6']
[2024-03-08T00:11:29.576+0530] {standard_task_runner.py:88} INFO - Job 543: Subtask unzip_archive
[2024-03-08T00:12:34.888+0530] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-03-08T00:12:34.891+0530] {process_utils.py:131} INFO - Sending 15 to group 1948. PIDs of all processes in the group: [1948]
[2024-03-08T00:12:34.891+0530] {process_utils.py:86} INFO - Sending the signal 15 to group 1948
[2024-03-08T00:12:34.893+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=1948, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='00:11:29') (1948) terminated with exit code -15
